---
abstract: 'turns baubles into trinkets'
author:
  - 'Jean-Christian HASSLER <jhassler@free.fr>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Debug-ZeroMQ
version: 0.001
